---
- name: Install Tomcat
  package:
    name: tomcat
    state: latest

- name: Ensure Tomcat root directory exists
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: Deploy index.html to tomcat_web_root
  teamplate:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}"/index.html
    mode: 0644

- name: Enable and start Tomcat
  service:
    name: tomcat
    enabled: true
    state: restarted